{"ClassName":"Microsoft.CSharp.RuntimeBinder.RuntimeBinderException","Message":"Operator '++' cannot be applied to operand of type 'string'","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at CallSite.Target(Closure , CallSite , Object )\r\n   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)\r\n   at Pizzeria.DAL.JsonData.SaveOrder(OrderViewModel order) in C:\\Sudarshan\\Notes\\Pizzeria\\Pizzeria\\Pizzeria.DAL\\JsonData.cs:line 19\r\n   at Pizzeria.BL.OrderBL.saveOrder(OrderViewModel order) in C:\\Sudarshan\\Notes\\Pizzeria\\Pizzeria\\Pizzeria.BL\\OrderBL.cs:line 16\r\n   at Pizzeria.Service.Controllers.OrderController.SaveOrder(OrderViewModel order) in C:\\Sudarshan\\Notes\\Pizzeria\\Pizzeria\\Pizzeria.Service\\Controllers\\OrderController.cs:line 19\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233088,"Source":"Anonymously Hosted DynamicMethods Assembly","WatsonBuckets":null}